### ISSUE TITLE
MacOs Wiki contains incorrect installation instructions

### ISSUE THREAD

**Issue by CelestialWren** [DrapNard/UndergroundShop#2]
**Is your feature request related to a problem? Please describe.**
    The installation instructions for MacOs are fundamentally flawed, as Proton cannot be enabled on Steam on MacOs. This led to a several hour process to install the game.

**Describe the solution you'd like**
Replace the WIP MacOs Installation section with the following:
**Prerequisites:**
1. Install [Brew](https://brew.sh/)
2. Install [Wine](https://formulae.brew.sh/cask/wine-stable#default)
3. Install [Winetricks](https://formulae.brew.sh/formula/winetricks#default)
4. Install [Wineskin Server](https://github.com/Gcenx/WineskinServer#how-to-install) via Brew
**Installation** 
1. Download the latest version of the MacOs [Launcher](https://github.com/DrapNard/InfiniteFusion-Launcher/releases) from the releases page.
2. Extract the downloaded lancher.
3. Open Wineskin Winery, the program installed from Wineskin Server.
4. Click the "+" to the left the "New Engines Available!" text.
5. Select the "WS11WineX64Bit3.6.0_D3DMetal" engine from the drop-down and confirm the download by clicking the "Download and Install" button.
6. Click the "Upgrade" button under wrapper version to ensure you have the latest wrapper version.
7. Select "Create New Blank Wrapper" and enter the name for the application you would like Infinite Fusion to be called.
8. Wait a bit for the wrapper to create, it is normal for this to take a while.
9. Once the wrapper has been created, launch the wrapper application, which will be under Applications with the name you gave it.
10. Click the middle "Winetricks" button and enter ".net" into the search field. Then, open the "dlls" section and check the box for ".netdesktop6"
11. Press the "Run" button to install this dependency, it's normal for this to take a bit.
12. Once the installation of .NET finishes, press the "Close" button.
13. Select the top "Install Software" button and select "Copy Folder Inside."
14. Grant the Wineskin permissions to where the launcher folder is and select that folder in the file system popup. 
15. A menu will ask what exe to launch normally, select the one that ends in "Infinite Fusion Launcher.exe", not "Updater.exe"
16. Press the "Ok" button.
17. Close the Wineskin window if it does not automatically close.
18. The installation is finished!

**Comment by DrapNard** [comment]
Thanks it's add to wiki
