### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by Welcometodahub** [DrapNard/UndergroundShop#3]
Whenever I try to use the launcher to download the game, I get an error about 10% in.

![Screenshot (2)](https://github.com/DrapNard/InfiniteFusion-Launcher/assets/108602572/5feb6642-38ba-4736-8079-6f2c430a7fb7)

I use Windows 11 and I have plenty of space on the drive the game is downloading on.

It also gives me an Extraction Error or something afterwards.

![Screenshot (3)](https://github.com/DrapNard/InfiniteFusion-Launcher/assets/108602572/7d44040a-53b2-4fb7-a871-3fa332f109bf)

**Comment by DrapNard** [comment]
This issue is already fixed in the next update 

The issues is cause by a obsolete technology for the download method
