### ISSUE TITLE
The calculator can only support v5

### ISSUE THREAD

**Issue by XGroudon** [DrapNard/UndergroundShop#4]
**Is your feature request related to a problem? Please describe.**
The current calculator can only support v5 and the game has been updated to v6

**Describe the solution you'd like**
Update this calculator to with new Pokémons.

**Describe alternatives you've considered**
Would it be possible to add existing v6 calculators, such as [this](https://infinite-fusion-calculator.com/).

**Additional context**

**Comment by DrapNard** [comment]
The link will be update

**Comment by XGroudon** [comment]
> The link will be update

Thanks for your work!
