### ISSUE TITLE
Can we help translating the game into another language (french here)

### ISSUE THREAD

**Issue by brotherrick** [DrapNard/UndergroundShop#5]
**Is your feature request related to a problem? Please describe.**
Not a problem at all. I was thinking about working on some **french translation** for the game because someone asked me.

**Describe the solution you'd like**
Would it be possible to extract all the text content and give it to us so that we can work on it on our side and then send it back once complete? I'm used to the basic method with RPG maker debug menu, but it doesn't work in this case so I'm asking for some more help.

**Describe alternatives you've considered**
You might not be interested in this, in this case, we will not proceed any further.

**Additional context**
(Also saw that some other guys might have wanted to work on a german version).
Thanks, have a nice day.

**Comment by DrapNard** [comment]
Do you ask to Chardub ? And it's not the place here

**Comment by Purple-fox-Pif** [comment]
Je veux bien aider

**Comment by brotherrick** [comment]
@DrapNard Hmmm yeah, i thought i could contact him from here, that might have been a mistake on my side, I will try from the discord then I guess? (didn't join it before)

@Purple-fox-Pif Il faut déjà queue j'arrive à récupérer l'extrait texte en effect, mais tu peux m'envoyer un message/ me demander en ami depuis le serveur discord infinite fusion où mon surnom est Goulagmaster.

**Comment by Naurth** [comment]
Je suis bon en anglais et fan du projet, j’ai de plus une belle syntaxe et sais jongler avec les mots et trouver des références si cela est nécessaire car certaines réf anglaises sont inconnus pour nos membres de l’hexagone 

Comment vous rejoindre ?
